import type { Metadata } from "next";
import { Geist, Geist_Mono, Instrument_Serif } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import ConditionalNavbar from "@/components/navbar/ConditionalNavbar";
import RevealMount from "@/components/home/RevealMount";
import SplashScreen from "@/components/SplashScreen";
import { AuthProvider } from "@/providers/AuthProvider";
import { LocaleProvider } from "@/providers/LocaleProvider";
import AppPadding from "@/components/AppPadding";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const instrumentSerif = Instrument_Serif({
  variable: "--font-instrument-serif",
  subsets: ["latin"],
  weight: "400",
  display: "swap",
});

const openSauce = localFont({
  src: "./fonts/OpenSauceOne-Bold.ttf",
  variable: "--font-open-sauce",
  weight: "700",
  display: "swap",
});

const blanquotey = localFont({
  src: "../../public/fonts/Blanquotey.ttf",
  variable: "--font-blanquotey",
  weight: "400",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${instrumentSerif.variable} ${openSauce.variable} ${blanquotey.variable} antialiased bg-background`}
      >
        <LocaleProvider>
          <AuthProvider>
            <SplashScreen />
            {/* <ConditionalNavbar /> */}
            <RevealMount />
            <AppPadding>{children}</AppPadding>
          </AuthProvider>
        </LocaleProvider>
      </body>
    </html>
  );
}
